version: "2"
services:
  speedlogger-web:
    image: matthewtoye/internet-speed-logger
    ports:
      - ${EXTERNAL_PORT}:3000
    depends_on:
      - mongo
    restart: always
    volumes:
      - config:/data/config
  speedlogger-runner:
    image: matthewtoye/internet-speed-logger
    depends_on:
      - speedlogger-web
    restart: always
    entrypoint:
      - node
      - run-speedtest.js
      - daemon
      - ${TIME_BETWEEN_TESTS}
      - ${SPEEDTEST_OR_PINGTEST}
    volumes:
      - config:/data/config
  mongo:
    image: bitnami/mongodb
    expose:
      - "27017"
    environment:
      - MONGODB_USERNAME=speedtest
      - MONGODB_PASSWORD=speedtest
      - MONGODB_DATABASE=speedtest
    volumes:
      - mongoDB:/bitnami
volumes:
   mongoDB:
      driver: local
   config:
      driver: local
