version: "2.4"
services:
  speedlogger-web:
    build:
      context: https://github.com/matthewtoye/internet-speed-logger.git
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    volumes:
      - config:/data/config
  speedlogger-runner:
    build:
      context: https://github.com/matthewtoye/internet-speed-logger.git
      dockerfile: Dockerfile
    depends_on:
      - speedlogger-web
    restart: always
    entrypoint:
      - node
      - run-speedtest.js
      - daemon
    volumes:
      - config:/data/config
  mongo:
    image: bitnami/mongodb
    expose:
      - "27017"
    environment:
      - MONGODB_USERNAME=speedtest
      - MONGODB_PASSWORD=speedtest
      - MONGODB_DATABASE=speedtest
    volumes:
      - mongo:/bitnami
volumes:
    config:
    mongo:
